tunneling:
  host: '127.0.0.1'
  port: 3671
  local_ip: '127.0.0.1'
event_filter:
  - "*/*/*"
light:
  - name: 'center_strip'
    address: '1/0/1'
    state_address: '1/0/2'
  - name: 'center_ceil'
    address: '1/0/3'
    state_address: '1/0/4'
  - name: 'aisle_outer'
    address: '1/0/5'
    state_address: '1/0/6'
  - name: 'aisle_inner'
    address: '1/0/7'
    state_address: '1/0/8'
  - name: 'dining_strip'
    address: '1/0/9'
    state_address: '1/0/10'
  - name: 'dining_tv'
    address: '1/0/11'
    state_address: '1/0/12'
  - name: 'dining_spot'
    address: '1/0/13'
    state_address: '1/0/14'
  - name: 'dining_ceil'
    address: '1/0/15'
    state_address: '1/0/16'
  - name: 'north_balcony'
    address: '1/0/17'
    state_address: '1/0/18'
  - name: 'south_balcony'
    address: '1/0/19'
    state_address: '1/0/20'
  - name: 'living_spot'
    address: '1/0/21'
    state_address: '1/0/22'
  - name: 'living_strip'
    address: '1/0/23'
    state_address: '1/0/24'
  - name: 'living_ceil'
    address: '1/0/25'
    state_address: '1/0/26'
  - name: 'living_wall'
    address: '1/0/27'
    state_address: '1/0/28'
  - name: 'kitchen_ceil'
    address: '1/1/1'
    state_address: '1/1/2'
  - name: 'kitchen_strip'
    address: '1/1/3'
    state_address: '1/1/4'
  - name: 'guest_wash_spot'
    address: '1/2/1'
    state_address: '1/2/2'
  - name: 'guest_wash_toilet'
    address: '1/2/5'
    state_address: '1/2/6'
  - name: 'master_strip'
    address: '1/3/1'
    state_address: '1/3/2'
  - name: 'master_bed'
    address: '1/3/3'
    state_address: '1/3/4'
  - name: 'master_tv'
    address: '1/3/5'
    state_address: '1/3/6'
  - name: 'master_window'
    address: '1/3/7'
    state_address: '1/3/8'
  - name: 'master_ceil'
    address: '1/3/9'
    state_address: '1/3/10'
  - name: 'master_wash_ceil'
    address: '1/3/11'
    state_address: '1/3/12'
  - name: 'master_wash_spot'
    address: '1/3/13'
    state_address: '1/3/14'
  - name: 'master_wash_bath'
    address: '1/3/15'
    state_address: '1/3/16'
  - name: 'north_strip'
    address: '1/4/1'
    state_address: '1/4/2'
  - name: 'north_bed'
    address: '1/4/3'
    state_address: '1/4/4'
  - name: 'north_tv'
    address: '1/4/5'
    state_address: '1/4/6'
  - name: 'north_window'
    address: '1/4/7'
    state_address: '1/4/8'
  - name: 'north_ceil'
    address: '1/4/9'
    state_address: '1/4/10'
  - name: 'guest_entrance'
    address: '1/5/1'
    state_address: '1/5/2'
  - name: 'guest_bed'
    address: '1/5/3'
    state_address: '1/5/4'
  - name: 'guest_tv'
    address: '1/5/5'
    state_address: '1/5/6'
  - name: 'guest_window'
    address: '1/5/7'
    state_address: '1/5/8'
  - name: 'guest_ceil'
    address: '1/5/9'
    state_address: '1/5/10'
  - name: 'guest_strip'
    address: '1/5/11'
    state_address: '1/5/12'

switch:
  - name: 'guest_wash_fan'
    address: '1/2/3'
    state_address: '1/2/4'
  - name: 'master_wash_fan'
    address: '1/3/17'
    state_address: '1/3/18'
  - name: 'fresh_air_fan'
    address: '12/1/11'
    state_address: '12/1/139'
    
fan: 
  - name: 'living_ac1_volume'
    address: '12/3/1'
    state_address: '12/3/129'
    max_step: 5
  - name: 'living_ac2_volume'
    address: '12/3/2'
    state_address: '12/3/130'
    max_step: 5
  - name: 'dining_ac_volume'
    address: '12/3/3'
    state_address: '12/3/131'
    max_step: 5
  - name: 'kitchen_ac_volume'
    address: '12/3/4'
    state_address: '12/3/132'
    max_step: 5
  - name: 'master_ac_volume'
    address: '12/3/5'
    state_address: '12/3/133'
    max_step: 5
  - name: 'north_ac_volume'
    address: '12/3/6'
    state_address: '12/3/134'
    max_step: 5
  - name: 'guest_ac_volume'
    address: '12/3/7'
    state_address: '12/3/135'
    max_step: 5
  - name: 'fresh_air_volume'
    address: '12/3/11'
    state_address: '12/3/139'
    max_step: 2

climate:
  - name: 'living_ac1'
    on_off_address: '12/1/1'
    on_off_state_address: '12/1/129'
    controller_mode_address: '12/2/1'
    controller_mode_state_address: '12/2/129'
    controller_modes:
      - 'Heat'
      - 'Cool' 
      - 'Fan only'
      - 'Auto'
      - 'Dry'
    temperature_address: "12/5/129"
    target_temperature_address: '12/4/1'
    target_temperature_state_address: '12/4/129'
    min_temp: 16.0
    max_temp: 32.0
    temperature_step: 1.0
  - name: 'living_ac2'
    on_off_address: '12/1/2'
    on_off_state_address: '12/1/130'
    controller_mode_address: '12/2/2'
    controller_mode_state_address: '12/2/130'
    controller_modes:
      - 'Heat'
      - 'Cool' 
      - 'Fan only'
      - 'Auto'
      - 'Dry'
    temperature_address: "12/5/130"
    target_temperature_address: '12/4/2'
    target_temperature_state_address: '12/4/130'
    min_temp: 16.0
    max_temp: 32.0
    temperature_step: 1.0
  - name: 'dining_ac'
    on_off_address: '12/1/3'
    on_off_state_address: '12/1/131'
    controller_mode_address: '12/2/3'
    controller_mode_state_address: '12/2/131'
    controller_modes:
      - 'Heat'
      - 'Cool' 
      - 'Fan only'
      - 'Auto'
      - 'Dry'
    temperature_address: "12/5/131"
    target_temperature_address: '12/4/3'
    target_temperature_state_address: '12/4/131'
    min_temp: 16.0
    max_temp: 32.0
    temperature_step: 1.0
  - name: 'kitchen_ac'
    on_off_address: '12/1/4'
    on_off_state_address: '12/1/132'
    controller_mode_address: '12/2/4'
    controller_mode_state_address: '12/2/132'
    controller_modes:
      - 'Heat'
      - 'Cool' 
      - 'Fan only'
      - 'Auto'
      - 'Dry'
    temperature_address: "12/5/132"
    target_temperature_address: '12/4/4'
    target_temperature_state_address: '12/4/132'
    min_temp: 16.0
    max_temp: 32.0
    temperature_step: 1.0
  - name: 'master_ac'
    on_off_address: '12/1/5'
    on_off_state_address: '12/1/133'
    controller_mode_address: '12/2/5'
    controller_mode_state_address: '12/2/133'
    controller_modes:
      - 'Heat'
      - 'Cool' 
      - 'Fan only'
      - 'Auto'
      - 'Dry'
    temperature_address: "12/5/133"
    target_temperature_address: '12/4/5'
    target_temperature_state_address: '12/4/133'
    min_temp: 16.0
    max_temp: 32.0
    temperature_step: 1.0
  - name: 'north_ac'
    on_off_address: '12/1/6'
    on_off_state_address: '12/1/134'
    controller_mode_address: '12/2/6'
    controller_mode_state_address: '12/2/134'
    controller_modes:
      - 'Heat'
      - 'Cool' 
      - 'Fan only'
      - 'Auto'
      - 'Dry'
    temperature_address: "12/5/134"
    target_temperature_address: '12/4/6'
    target_temperature_state_address: '12/4/134'
    min_temp: 16.0
    max_temp: 32.0
    temperature_step: 1.0
  - name: 'guest_ac'
    on_off_address: '12/1/7'
    on_off_state_address: '12/1/135'
    controller_mode_address: '12/2/7'
    controller_mode_state_address: '12/2/135'
    controller_modes:
      - 'Heat'
      - 'Cool' 
      - 'Fan only'
      - 'Auto'
      - 'Dry'
    temperature_address: "12/5/135"
    target_temperature_address: '12/4/7'
    target_temperature_state_address: '12/4/135'
    min_temp: 16.0
    max_temp: 32.0
    temperature_step: 1.0
    
sensor:
  - name: 'PM25'
    state_address: '15/0/0'
    type: 'ppm'
    sync_state: "expire 5"
